package main

import (
	"context"
	"fmt"
	_ "github.com/go-park-mail-ru/2021_2_A06367/docs" // docs is generated by Swag CLI, you have to import it.
	actorsDelivery "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/actors/delivery/http"
	actorsRepository "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/actors/repo"
	actorsUsecase "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/actors/usecase"
	authDelivery "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/auth/delivery/http"
	authRepository "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/auth/repo"
	authUsecase "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/auth/usecase"
	"github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/config"
	filmsDelivery "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/films/delivery/http"
	filmsRepository "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/films/repo"
	filmsUsecase "github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/films/usecase"
	"github.com/go-park-mail-ru/2021_2_A06367/internal/pkg/middleware"
	"github.com/gorilla/csrf"

	//"github.com/gorilla/csrf"
	"github.com/gorilla/mux"
	"github.com/jackc/pgx/v4/pgxpool"
	"go.uber.org/zap"
	"log"
	"net/http"
	"os"

	httpSwagger "github.com/swaggo/http-swagger"
)

// @title LimeTV API
// @version v0.1.0
// @description This is a service for LimeTV project "A06367"
// @contact.name Lelya Kochkarova, Ivan Chernov, Slava Rianov
// @contact.email kochkarova.lelya@gmail.com, chernov-ivan.1998@yandex.ru, slavarianov@yandex.ru
// @host http://3.67.182.34:8080
// @BasePath /
func main() {
	if err := run(); err != nil {
		log.Print(err)
		os.Exit(1)
	}
}
func run() error {
	r := mux.NewRouter()

	key, err := config.GetCsrfToken()
	if err != nil {
		return err
	}
	protect := csrf.Protect(key, csrf.Secure(false))

	r.Use(middleware.CORSMiddleware)
	srv := http.Server{Handler: r, Addr: fmt.Sprintf(":%s", "8000")}

	logger, _ := zap.NewProduction()
	defer logger.Sync()
	if err != nil {
		return err
	}
	defer logger.Sync()
	zapSugar := logger.Sugar()

	conn, err := config.GetConnectionString()
	if err != nil {
		return err
	}

	pool, err := pgxpool.Connect(context.Background(), conn)
	if err != nil {
		return err
	}

	encrypter := authUsecase.NewEncrypter()
	tokenGenerator := authUsecase.NewTokenator()
	authRepo := authRepository.NewAuthRepo(pool, zapSugar)
	authUse := authUsecase.NewAuthUsecase(authRepo, tokenGenerator, encrypter, zapSugar)
	authHandler := authDelivery.NewAuthHandler(authUse, zapSugar)

	filmsRepo := filmsRepository.NewFilmsRepo(pool, zapSugar)
	filmsUse := filmsUsecase.NewFilmsUsecase(filmsRepo, zapSugar)
	filmsHandler := filmsDelivery.NewFilmsHandler(filmsUse, zapSugar)

	actorsRepo := actorsRepository.NewActorsRepo(pool, zapSugar)
	actorsUse := actorsUsecase.NewActorsUsecase(actorsRepo, zapSugar)
	actorsHandler := actorsDelivery.NewActorsHandler(actorsUse, zapSugar)

	m := middleware.NewMiddleware(zapSugar)

	auth := r.PathPrefix("/users").Subrouter()
	auth.Use(protect)
	{
		auth.HandleFunc("/secure", authHandler.Token).Methods(http.MethodGet)
		auth.HandleFunc("/login", authHandler.Login).Methods(http.MethodPost)
		auth.HandleFunc("/logout", authHandler.Logout).Methods(http.MethodPost, http.MethodOptions)
		auth.HandleFunc("/signup", authHandler.SignUp).Methods(http.MethodPost)
		auth.HandleFunc("/auth", authHandler.AuthStatus).Methods(http.MethodGet)
		auth.HandleFunc("/profile/{id}", authHandler.GetProfile).Methods(http.MethodGet)
		auth.HandleFunc("/profile/{id}/follow", authHandler.Follow).Methods(http.MethodPost)
		auth.HandleFunc("/profile/{id}/unfollow", authHandler.Unfollow).Methods(http.MethodDelete)
	}

	film := r.PathPrefix("/films").Subrouter()
	{
		film.HandleFunc("/genre/{genre}", filmsHandler.FilmByGenre).Methods(http.MethodGet)
		film.HandleFunc("/selection/{selection}", filmsHandler.FilmBySelection).Methods(http.MethodGet)
		film.HandleFunc("/film/{film_id}", filmsHandler.FilmById).Methods(http.MethodGet)
		film.HandleFunc("/selection/actor/{actor_id}", filmsHandler.FilmByActor).Methods(http.MethodGet)
		film.HandleFunc("/selection/user/personal", filmsHandler.FilmsByUser).Methods(http.MethodGet)
		film.HandleFunc("/selection", filmsHandler.FilmStartSelection).Methods(http.MethodGet)
	}

	actors := r.PathPrefix("/actors").Subrouter()
	{
		actors.HandleFunc("/actor/{id}", actorsHandler.ActorsById).Methods(http.MethodGet)
	}
	// swag init -g ./cmd/main/main.go
	r.PathPrefix("/api-docs").Handler(httpSwagger.WrapHandler)

	r.Use(m.LogRequest)

	http.Handle("/", protect(r))
	log.Print("main running on: ", srv.Addr)
	return srv.ListenAndServe()
}
