version: '2.0'

services:
  db-auth:
    restart: always
    image: postgres:latest
    volumes:
      - ./build/init.sql:/docker-entrypoint-initdb.d/create-db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - 5433:5432
