// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson71c15eefDecodeGithubComGoParkMailRu20212A06367InternalModels(in *jlexer.Lexer, out *UMoney) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "operation_id":
			out.OperationId = string(in.String())
		case "notification_type":
			out.NotificationType = string(in.String())
		case "datetime":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.Datetime).UnmarshalJSON(data))
			}
		case "sha1_hash":
			out.Sha1Hash = string(in.String())
		case "sender":
			out.Sender = string(in.String())
		case "codepro":
			out.Codepro = string(in.String())
		case "currency":
			out.Currency = string(in.String())
		case "amount":
			out.Amount = string(in.String())
		case "withdraw_amount":
			out.WithdrawAmount = string(in.String())
		case "label":
			out.Label = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson71c15eefEncodeGithubComGoParkMailRu20212A06367InternalModels(out *jwriter.Writer, in UMoney) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"operation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.OperationId))
	}
	{
		const prefix string = ",\"notification_type\":"
		out.RawString(prefix)
		out.String(string(in.NotificationType))
	}
	{
		const prefix string = ",\"datetime\":"
		out.RawString(prefix)
		out.Raw((in.Datetime).MarshalJSON())
	}
	{
		const prefix string = ",\"sha1_hash\":"
		out.RawString(prefix)
		out.String(string(in.Sha1Hash))
	}
	{
		const prefix string = ",\"sender\":"
		out.RawString(prefix)
		out.String(string(in.Sender))
	}
	{
		const prefix string = ",\"codepro\":"
		out.RawString(prefix)
		out.String(string(in.Codepro))
	}
	{
		const prefix string = ",\"currency\":"
		out.RawString(prefix)
		out.String(string(in.Currency))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"withdraw_amount\":"
		out.RawString(prefix)
		out.String(string(in.WithdrawAmount))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UMoney) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson71c15eefEncodeGithubComGoParkMailRu20212A06367InternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UMoney) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson71c15eefEncodeGithubComGoParkMailRu20212A06367InternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UMoney) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson71c15eefDecodeGithubComGoParkMailRu20212A06367InternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UMoney) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson71c15eefDecodeGithubComGoParkMailRu20212A06367InternalModels(l, v)
}
