name: Netflix v2 build

on:
  push:
    branches:
      - main
      - grpc-magic
      - ktlh-raitings
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run tests
        run:  go test -v -coverpkg=./... -coverprofile=profile.cov ./... && go tool cover -func profile.cov
  prebuild:
    name: prebuild
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 1
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - lint
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2021_2_A06367 && git pull
      - name: Build containers
        uses: appleboy/ssh-action@master
        with:
          timeout: 30m
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2021_2_A06367 && docker-compose build
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2021_2_A06367 && docker-compose down && docker rm $(docker ps -aq) && docker-compose up -d

