name: Netflix v2 build

on:
  push:
    branches:
      - auth-update
jobs:
  prebuild:
    name: prebuild
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 0
    # TODO: добавить шаг с тестами
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Test
        run: go test ./...
    # TODO: добавить шаг с линтером
      - name: golang-ci
        uses: Mushus/golangci-linter@v1
