name: Netflix v2 build

on:
  push:
    branches:
      - main
      - grpc-magic
      - ktlh-raitings
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Run tests
        run: go test  -v -coverprofile=coverage.out.tmp -coverpkg=./...  ./... && cat coverage.out.tmp | grep -v _mock.go | grep -v _easyjson.go | grep -v .pb.go | grep -v _grpc.go > coverage.out && go tool cover -func=coverage.out
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2021_2_A06367 && git pull
      - name: Build containers
        uses: appleboy/ssh-action@master
        with:
          timeout: 30m
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2021_2_A06367 && docker-compose build
      - name: Restart service
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: cd /home/ubuntu/backend/2021_2_A06367 && docker-compose down && docker rm $(docker ps -aq) && docker-compose up -d

