name: Netflix v2 build

on:
  push:
    branches: [ dev ] # Пока собираем только дев-ветку

jobs:
  prebuild:
    name: prebuild
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 0
    # TODO: добавить шаг с тестами
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.42
