name: Netflix v2 build

on:
  push:
    branches:
      - auth-update
jobs:
  prebuild:
    name: prebuild
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo 0
    # TODO: добавить шаг с линтером
      - name: golang-ci
        uses: Mushus/golangci-linter@v1
    # TODO: добавить шаг с тестами
      - name: tests
        run: |
          cd ./internal
          go test ./...